### ISSUE TITLE
Log file remains open (but deleted) after profiling

### ISSUE THREAD

**Issue by Jongy** [async-profiler/async-profiler#450]
The log file opened by `Log::open` remains open after profiling.
It will be closed & re-created upon the next attach, but until that point it remains open, taking up an fd, and anyway it's inaccessible because `profiler.sh` removes the log file after reading:
```
l-wx------ 1 8888 8888 64 Aug  2 00:30 17 -> '/tmp/async-profiler-log.1827754.1827654 (deleted)'
```
I suggest we close it (and swap back to `stdout`) after stop/dump commands? Not sure where's the correct spot to add such code so opening an issue instead :)

**Comment by apangin** [comment]
The problem is that the agent does not know if/when the log files are deleted - it's the feature of the specific launcher.
So I made async-profiler close file only when it knows the command was invoked by `asprof` launcher. It uses the log file name to recognize the launcher. Not ideal but working solution.
