### ISSUE TITLE
--loop option not supported in jni mode

### ISSUE THREAD

**Issue by darl** [async-profiler/async-profiler#637]
`--loop` option supported only when `Arguments.persistent == true`.
When starting profiler via JNI call its false.

Is it feasible to fix?

**Comment by apangin** [comment]
`loop` option was added primarily for the case of starting profiler as an agent.
When running profiler using Java API within the same process, you have full control over the profiling cycle - it's easy to start, stop and repeat profiling session programmatically whenever is needed.

While it's possible to make `loop` option work with Java API, this will not add something essentially new that can't be easily implemented using the existing API.

**Comment by darl** [comment]
I'm afraid I'm losing some of the data between `stop` and `start`.

Perhaps it's possible to add new command to rotate output JFR file.

**Comment by offermannu** [comment]
> When running profiler using Java API within the same process, you have full control over the profiling cycle

This is not necessarily true in production environments because access to the Shell is often not possible on demand. In our case, we have remote access via JMX, allowing us to start and stop profiling sessions as needed - but unfortunately this does not apply to continuous profiling. As @darl noted there is an extra "persistent" flag that explicitely denies continuous profiling via JNI. If the added value is not so high, then maybe the cost-benefit is not so bad, if it would help some users 😉...

**Comment by apangin** [comment]
Added support for `loop` and `timeout` options in all modes.
