### ISSUE TITLE
Support non interleaving multi-event profiling

### ISSUE THREAD

**Issue by tomershafir** [async-profiler/async-profiler#798]
Concurrent multi-event collection can interfere each other and skew the results, for example, a bad case, where an app in steady state allocates and computes correspondingly with each other with respect to sampling config, threads performing tlab sampling may be captured by cpu profiler, skewing the flame graph.

A solution may be a fixed wall time window mechanism. Then, you can for example on a cpu-bound app sample cpu 1m then sample tlab 2m then sleep 2m. I may be able to help if you think its useful

**Comment by apangin** [comment]
Thank you for the feedback.

Collection of all events together does not seem a big problem. The ability of the profiler to show its own overhead is more like a feature than a defect: in what sense the flame graph is skewed, when it shows the actual picture, even if it contains something besides the user code? Similarly, async-profiler shows CPU time spent in the JVM, unlike JFR which samples only Java code. After all, it's possible to omit undesired stack traces from the profile by using `-X` / `--exclude` option.

If, for any reason, you wish to collect multiple events one by one, you can do it by starting multiple profiling sessions with different event arguments. Note that when you use `resume` command with the same output file (`-f`) as in previous session, new data will be appended to the existing file instead of overwriting it.

**Comment by tomershafir** [comment]
I still think its a bad thing it takes the band of the user app in the profile, and it may also be useful to manage multi-event overhead. Anyway, closed this one because will try to add it to a wrapper lib and start/stop async-profiler.
