### ISSUE TITLE
About none heap allocation profiling

### ISSUE THREAD

**Issue by yanglong1010** [async-profiler/async-profiler#828]
hi

Using JDK `heapdump` and the `alloc engine` of `async-profiler` can effectively diagnose heap-related problems.
But for `non-heap` direct memory, currently known diagnostic tools are:
* For JDK 15 and above, you can use [jdk.DirectBufferStatistics](https://bugs.openjdk.org/browse/JDK-8238665) to check the capacity and usage, but it is completely different from `jdk.ObjectAllocationInNewTLAB` and does not support finding hot spots.
* You can trigger `heapdump` and then count the `java.nio.DirectByteBuffer` object, but this way you can only get the capacity and usage.

Is it possible to add a `direct memory` profiling engine like `async-profiler`'s `lockTracer`, and use `interval=1m` or `events/timeUnit` to control the overhead.

**Comment by apangin** [comment]
I have no plans to add a separate engine for Direct ByteBuffers, since this is just a special case of native memory profiling.
See #491, #453 for the discussion of `nativemem` feature. I also have a prototype for profiling malloc/free calls without LD_PRELOAD. It will likely appear in one of the nearest releases.
