### ISSUE TITLE
Crash inside logging initialisation

### ISSUE THREAD

**Issue by zuevmaxim** [async-profiler/async-profiler#834]
Hi! We have a crash inside the VM call during logs initialisation. Can async-profiler cause it?

[java_error_in_idea_31844.log](https://github.com/async-profiler/async-profiler/files/13238603/java_error_in_idea_31844.log)

We use a patched version of the async-profiler built from master d29cb86bd0d663ffe65010c412ee360c67fbb274 (I can share dylib in DM)

**Comment by apangin** [comment]
The assertion error means an unhandled JNI exception has occurred in `AttachListener` thread before execution of a diagnostic command. The only scenario I can imagine is when `env->NewStringUTF` throws `OutOfMemoryError`. This is an unlikely event, but the crash report indeed indicates a low heap memory condition with 85 OutOfMemoryErrors happened. I committed the fix for such a case.

**Comment by zuevmaxim** [comment]
Thank you!
