### ISSUE TITLE
[ERROR] Could not set pthread hook

### ISSUE THREAD

**Issue by Apeksh742** [async-profiler/async-profiler#838]
Hi team,

I am receiving this error `[ERROR] Could not set pthread hook` when trying to use async profiler on a container.

I have also given `SYS_ADMIN` capability to the container and is hosted on an ec2 instance. I tried to use the async profiler from the host too but receiving the same error. Any help would be appreciated.

Thanks

**Comment by apangin** [comment]
What are OS, JDK and Profiler versions?

**Comment by Apeksh742** [comment]
1. Os - `Linux x86_64 `
2. java specs:
```
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)
```
3. profiler version: `async-profiler-2.9-linux-x64`

**Comment by apangin** [comment]
Does container run Alpine Linux? Which version?

Please try the newest early access version from `master`, which has the issue likely fixed:
 - If running on the host: https://profiler.tools/builds/async-profiler-3.0-ea-linux-x64.tar.gz
 - If running inside Alpine container: https://profiler.tools/builds/async-profiler-3.0-ea-linux-musl-x64.tar.gz

**Comment by Apeksh742** [comment]
Thanks https://profiler.tools/builds/async-profiler-3.0-ea-linux-x64.tar.gz worked for me.
I have one more query when I use this the console shows me warning of 
```
[WARN] Kernel symbols are unavailable due to restrictions. Try
sysctl kernel.kptr_restrict=0
sysctl kernel.perf_event_paranoid=1
```
I have used this these commands also but get the same warning. So what impact does it have and how to get rid of it?

**Comment by apangin** [comment]
@Apeksh742 "Kernel symbols are unavailable" message means the operating system configuration does not allow an unprivileged application to obtain kernel stack traces. In this case, profiler works absolutely fine, except that it does not show where exactly CPU time is spent inside system calls. If you don't need this level of details, you can completely ignore the above warning.

If you want async-profiler to collect kernel stack traces, run the following commands on the host (not inside a container) under a privileged user (root):
```
sysctl kernel.kptr_restrict=0
sysctl kernel.perf_event_paranoid=1
```

Otherwise, if you are fine with user-mode stacks only, add `--all-user` option to suppress the warning.
