### ISSUE TITLE
`timeout` in native mode does not work

### ISSUE THREAD

**Issue by abextm** [async-profiler/async-profiler#840]
Using 6ab9f83aec0e4d216d3a5b911a6123db6139c544
Running `LD_PRELOAD=libasyncProfiler.so ASPROF_COMMAND="start,event=cpu,file=test.html,timeout=5" glxgears` doesn't ever write `test.html`.
This is because the timer thread uses `_agent_args` instead of `_preload_args`, regardless of what actually started the Profiler. Making everything use a single `Arguments` instance seems to work correctly.

**Comment by apangin** [comment]
Thanks, the problem is understood. I'll see how to fix it.

As a workaround, you may use `jfr` output format (i.e. replace `file=test.html` with `file=test.jfr`). In this case, profiler will correctly stop and dump results after the given timeout. You may then use `converter.jar` to convert `jfr` to a flame graph.

**Comment by apangin** [comment]
Added support for loop and timeout options in all modes.
