### ISSUE TITLE
is https://github.com/async-profiler/async-profiler/issues/154 already fixed in latest async profiler?

### ISSUE THREAD

**Issue by zdyj3170101136** [async-profiler/async-profiler#850]
i find that in https://github.com/async-profiler/async-profiler/issues/154.

seems start async profiler, use asprof start or asprof stop would possible crash JVM.

only -agentpath could fix this problem, is this right?

**Comment by zdyj3170101136** [comment]
i use this command to continous profiling, every 60 minutes run once.
```
asprof start --cstack dwarf -d 59 -o jfr -f /tmp/pid.jfr pid
asprof stop pid
```

**Comment by zdyj3170101136** [comment]
https://bugs.openjdk.org/browse/JDK-8212155  is only fixed in java 17, this means i should stop all async profiler in prod, cause my java version is 1.8.

is there any possible way to fix problem [154 ](https://github.com/async-profiler/async-profiler/issues/154) by not upgrading the process java version.

**Comment by apangin** [comment]
It's a JVM bug, not async-profiler's bug

**Comment by apangin** [comment]
Creating a new issue to discuss an existing one is an abuse of GitHub issues (sorry, just mentioned that as it's not the first time I notice this pattern). Please comment on an existing ticket or start a discussion on the corresponding GitHub section.

As to the question - the referenced issue has all the information: it's a JVM bug and has been fixed in OpenJDK. Creating a workaround in async-profiler is feasible, but is not our top priority, since the bug is very rare and occurs only on old JDK versions.
