### ISSUE TITLE
Get rid of libstdc++ dependency

### ISSUE THREAD

**Issue by apangin** [async-profiler/async-profiler#872]
Currently, async-profiler uses standard C++ library classes such as:
 - IO streams
 - std::string
 - std::map
 - std::vector

This makes async-profiler depend on `libstdc++.so`, which causes certain compatibility issues.
 - async-profiler built on a newer Linux distribution does not work with older distributions;
 - libstdc++ is not preinstalled on Alpine Linux;
 - a statically linked async-profiler binary becomes too large.

I suggest rewriting relevant parts of async-profiler without use of libstdc++ classes. This will allow building a compact async-profiler binary that works both on glibc and musl libc.

**Comment by korniltsev** [comment]
Is someone already working on it? 


The reason Im asking is because Im linking libstdc++  statically on centos and when I try to use this library on alpine, dynamic linker is unable to load async-profiler which built this way. There are two reasons for this failure:

1. I found this set of function dependencies and `__strftime_l` seem to not exist in musl
```
__strftime_l => 
std::__timepunct<char>::_M_put <=
std::time_put<char,std::ostreambuf_iterator<char>>::do_put <=
vtable for'std::time_put<char, std::ostreambuf_iterator<char>> 
```
2.    async-profiler end up `DT_NEED` `ld-linux-x86-64.so.2`  which is likely there because `libstdc++` has it

When I rewrite io streams without libstdc++  , the resulting size of the binary goes from 1.4M to 500k and alpine is able to load the library (with one extra little hacky change just for POC - I manually binary patched to remove DT_NEED ld-linux-x86-64.so.2)

I would like to submit a PR rewriting  io streams. 
Is this something that can be accepted as an external contribution?
This could be a good first step towards removing libstdc++.

cc @apangin

**Comment by apangin** [comment]
Hi @korniltsev,
I haven't started implementing this yet.

Your proposal makes total sense to me. Did not expect that replacing streams only could make such a huge difference in binary size. With that in mind, getting rid of stdc++ classes completely may not be even needed: I think 500 KB binary with statically linked libstdc++ (comparing to 380K as of today) would be an acceptable trade-off.

**Comment by richardstartin** [comment]
FWIW we link our fork against libstdc++ statically and applied some compiler and linker flags (we build with gradle so we can't offer a direct patch if this information helps):

1. linker arg `-Wl,--exclude-libs,ALL` - prevents libstdc++ symbols from being exported (weak->local) so they can't collide if the host process loads an incompatible libstdc++ version. The same effect could also have been achieved with a linker script.
2. compiler flags `-fdata-sections, -ffunction-sections` in combination with linker arg `-Wl,--gc-sections` - this allows the linker to perform dead code elimination. We didn't measure impact on the object files directly at the time, but the reduction in the jar we package the various targets in was about 15%.

**Comment by apangin** [comment]
@richardstartin This is helpful; thank you for the hints!

**Comment by Jianqqiu-TCS** [comment]
I encountered the similar problem when I compile the code in glibc2.12 version，we add some new feature into async-profiler like thread local, which depends on c++11, do you have some suggestion to get rid of it

**Comment by apangin** [comment]
@Jianqqiu-TCS This has been already solved in #952

**Comment by apangin** [comment]
@Jianqqiu-TCS After changes in #952, async-profiler binaries no longer depend on libstdc++. You may use any C++ standard for compilation.

**Comment by apangin** [comment]
We've implemented workarounds for most of the issues with libstdc++.
Even though we haven't eliminated libstdc++ completely, it is no longer a problem.
