### ISSUE TITLE
Unsupported event type when trying to trace with a tracepoint

### ISSUE THREAD

**Issue by rustyrazorblade** [async-profiler/async-profiler#892]
I was trying to use the ability to use tracepoints on an Ubuntu box, but got an error that it's unsupported. 

```
ubuntu@ip-172-31-44-65:~$ sudo /usr/local/async-profiler/bin/asprof -e 'syscalls:sys_enter_open' -d 30 -f /tmp/flamegraph.html 4144
[ERROR] Unsupported event type
```

I wasn't sure if the docs had an error so I've also tried this:

```
ubuntu@ip-172-31-44-65:~$ sudo /usr/local/async-profiler/bin/asprof -e 'trace:syscalls:sys_enter_open' -d 30 -f /tmp/flamegraph-query-processor.html     4144
[ERROR] Unsupported event type
```

My system info:

```
ubuntu@ip-172-31-44-65:~$ uname -a
Linux ip-172-31-44-65 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

I'm not sure if the issue is my system, my command, or an issue with async profiler.

**Comment by apangin** [comment]
async-profiler resolves a symbolic name of a kernel tracepoint by reading debugfs filesystem (`/sys/kernel/debug`).
Typically, only a privileged user can read debugfs. This means, if a Java process runs under a non-root user, it will not be able to resolve tracepoint names. Note that `sudo asprof` does not help, since resolution happens in the context of a Java process, not in the context of asprof launcher.

A workaround is to resolve the symbolic tracepoint name manually and then pass `-e trace:id` as an event name.
Here is a sample command:
```
asprof -e trace:`sudo cat /sys/kernel/debug/tracing/events/syscalls/sys_enter_openat/id` --cstack dwarf -d 30 -f /tmp/flamegraph.html 4144
```

To simplify profiling tracepoints in the future, I've committed the fix that attempts to resolve tracepoints automatically in asprof. From now on, you can simply run `sudo asprof -e syscalls:sys_enter_openat ...` even if the target process works under a non-privileged user.

**Comment by apangin** [comment]
Additional notes:
 - Make sure `/sys/kernel/debug/tracing` directory exists. If not, you may need to mount debugfs filesystem:
    `mount -t debugfs none /sys/kernel/debug`
 - In modern glibc, `open()` function is usually implemented with `openat` syscall rather than `open`. Try profiling `syscalls:sys_enter_openat` if `syscalls:sys_enter_open` does not yield meaningful results.
