### ISSUE TITLE
[WARN] Unknown argument: cpu

### ISSUE THREAD

**Issue by ennishol** [async-profiler/async-profiler#917]
Changed order of the events produces a warning:
```
 asprof -e alloc,cpu,lock -d 10 -f tmp.jfr 583
[WARN] Unknown argument: cpu
Profiling for 10 seconds
```

and
```asprof -e cpu,alloc,lock -d 10 -f tmp.jfr 583```
works just fine

maybe it is worth fixing?

**Comment by apangin** [comment]
The preferred syntax for multi-event profiling is `-e cpu --alloc <interval> --lock <threshold>`
In fact, the variant `-e cpu,alloc,lock` works only because of a bug in the parser, and the proper fix would be to disallow this syntax entirely. However, since many people already got used to this format, I decided to leave it as a "feature".

**Comment by apangin** [comment]
Anyhow, the fix is trivial - let me push it.
I implemented it only for `cpu` event, though.

**Comment by ennishol** [comment]
Thank you very much for the fix and for explaining the right usage!
