### ISSUE TITLE
What's the exact overhead of using cpu profiling?

### ISSUE THREAD

**Issue by choxsword** [async-profiler/async-profiler#926]
As stated in the introduction,  async-profiler is a low-overhead tool, but it doesn't specify how low the overhead actually is.

**Comment by apangin** [comment]
The runtime overhead of the profiler depends on many factors, such as:
- specific application;
- Java and OS version;
- hardware;
- environment;
- profiler configuration.

Typically, with the default parameters, CPU overhead of the profiler is less than 1%, but it may vary depending on the particular application, number of threads, stack depth, cpu utilization, etc.

Due to the _sampling_  nature of the profiler, its overhead is directly manageable with `-i` option: the longer is profiling interval, the less is the overhead. For example, if you set `-i 100ms`, the overhead will be roughly 10x smaller comparing to the overhead with the default interval (which is 10ms),
