### ISSUE TITLE
build error when running make

### ISSUE THREAD

**Issue by choxsword** [async-profiler/async-profiler#932]
g++ -O3 -fno-omit-frame-pointer -fvisibility=hidden -Wl,-z,defs -Wl,-z,nodelete -fwhole-program -momit-leaf-frame-pointer -DPROFILER_VERSION=\"2.7\" -I/data/home/scottxiao/wn-dep/java/j2sdk-image/include -I/data/home/scottxiao/wn-dep/java/j2sdk-image/include/linux -fPIC -shared -o build/libasyncProfiler.so -xc++ - -ldl -lpthread -lrt
In file included from <stdin>:32:0:
src/perfEvents_linux.cpp:566:2: warning: #warning "Compiling without LBR support. Kernel headers 4.1+ required" [-Wcpp]
 #warning "Compiling without LBR support. Kernel headers 4.1+ required"
  ^

**Comment by apangin** [comment]
This is not an error, this is a warning.
It says that async-profiler is compiled without support for [LBR (Last Branch Record)](https://github.com/async-profiler/async-profiler/issues/215#issuecomment-617443443). If you don't need this feature, you may ignore the warning. Otherwise, install Linux Kernel Headers package with the version 4.1 or newer.
