### ISSUE TITLE
asprof list jps is empty

### ISSUE THREAD

**Issue by pendula95** [async-profiler/async-profiler#954]
### Describe the bug

I am using 
```
java -version
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.3.0.9-1.0.1) (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.3.0.9-1.0.1) (build 21.0.3+9-LTS, mixed mode, sharing)
```

```
uname -a
Linux master 5.4.17-2136.332.5.2.el8uek.x86_64 #3 SMP Tue Jun 11 17:58:26 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux
```

```
sudo dmidecode -s system-product-name
VirtualBox
```

Running any asprof does not  result in any error but finishes but no output is generated.
Example:
```
./asprof -d 15 -e cpu -f flamegraph.html 1734
Profiling for 15 seconds
Done

ll
total 64
-rwxr-xr-x. 1 root root 63136 Jan 20 23:25 asprof
```

As a final nail in the confine, running this command returns an empty list
```
asprof list jps
```

What am I doing wrong?

### Async-profiler version

async-profiler-3.0-linux-x64

**Comment by apangin** [comment]
Looks similar to #885 or #948.
Did you compile async-profiler yourself or used prebuilt binaries?
Did you try profiling JDK 17 (or any other version below 21)?

**Comment by apangin** [comment]
Thank you for the update. I think I understand the problem now.

Target JVM failed to load async-profiler library, most likely because the JVM process does not have access to the directory `/root/async-profiler-3.0-linux-x64`. It's not surprising since the JVM runs under a different user, but the directory with the profiler is owner by `root`.

Move profiler to some other directory that is readable by the JVM user.

There was no error message with JDK 21 because another issue - #885. The fix for that one has been already committed.

**Comment by pendula95** [comment]
Thank you @apangin, I have tried the suggested solution and it works. 
As this is no longer bug and error reporting is already solved I will close this issue.
